name: uberneta
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  html: ^0.15.0
  universal_html: ^2.2.4
  flutter_pdfview: ^1.0.0
  dio: ^5.2.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.15
  provider: ^6.0.0
  bcrypt: ^1.1.3
  mailer: ^6.2.0
  ftpconnect: ^2.0.7
  crypto: ^3.0.0
  dartssh2: ^2.10.0
  syncfusion_flutter_calendar: ^28.2.7
  flutter_localization: ^0.2.2
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.2.2
  file_selector: ^1.0.3
  flutter_zoom_drawer: ^3.2.0
  flutter_local_notifications: ^18.0.1
  pdf: ^3.11.1
  printing: ^5.13.4
  html_to_pdf: ^0.8.1
  open_file: ^3.5.10
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  change_app_package_name: ^1.1.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  font_awesome_flutter: ^10.1.0
  flutter_slidable: ^4.0.0
  file_picker: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  syncfusion_flutter_pdfviewer: 28.2.12

dev_dependencies:
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "img/avatar.png"
  adaptative_icon_background: "ffffff"
  adaptative_icon_foreground: "img/avatar.png"

flutter:
  uses-material-design: true

  assets:
    - img/logo-uberneta-limpia.png
    - img/logo-uberneta.png
  fonts:
    - family: Eurocl15
      fonts:
        - asset: fonts/Eurocl15.ttf
        - asset: fonts/timesnewroman.ttf
        - asset: fonts/OpenSansRegular.ttf
        - asset: fonts/OpenSansBold.ttf
